### ISSUE TITLE
"No class named mehrwert\Phpmyadmin\Hooks\BeUserAuthLogOffHook" exception after log in

### ISSUE THREAD

**Issue by Abdull** [mehrwert/TYPO3-phpMyAdmin#41]
I just did `composer update` on my TYPO3 installation, updating it from `v9.5.13` to `v9.5.14`.

During this process, `mehrwert/phpmyadmin` got updated from `5.4.0` to `5.6.1`.

Since then, trying to log in to the TYPO3 backend gives an _Oops, an error occurred!_ web interface response.

The TYPO3 log gives further information:

```
Fri, 13 Mar 2020 12:34:45 +0100 [CRITICAL] request="d65c876cfbeac" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1294585866: No class named mehrwert\Phpmyadmin\Hooks\BeUserAuthLogOffHook | InvalidArgumentException thrown in file /var/www/typo3/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3599. Requested URL: https://www.example.com/typo3/?loginProvider=1433416747 - {"TYPO3_MODE":"BE","exception":"InvalidArgumentException: No class named mehrwert\\Phpmyadmin\\Hooks\\BeUserAuthLogOffHook in /var/www/typo3/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php:3599\nStack trace:\n#0 /var/www/typo3/public/typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php(1064): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::callUserFunction('mehrwert\\\\Phpmya...', Array, Object(TYPO3\\CMS\\Core\\Authentication\\BackendUserAuthentication))\n#1 /var/www/typo3/public/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php(2809): TYPO3\\CMS\\Core\\Authentication\\AbstractUserAuthentication->logoff()\n#2 /var/www/typo3/public/typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php(652): TYPO3\\CMS\\Core\\Authentication\\BackendUserAuthentication->logoff()\n#3 /var/www/typo3/public/typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php(413): TYPO3\\CMS\\Core\\Authentication\\AbstractUserAuthentication->checkAuthentication()\n#4 /var/www/typo3/public/typo3/sysext/core/Classes/Core/Bootstrap.php(964): TYPO3\\CMS\\Core\\Authentication\\AbstractUserAuthentication->start()\n#5 /var/www/typo3/public/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(63): TYPO3\\CMS\\Core\\Core\\Bootstrap::initializeBackendUser()\n#6 /var/www/typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#7 /var/www/typo3/public/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(72): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#8 /var/www/typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#9 /var/www/typo3/public/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#10 /var/www/typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#11 /var/www/typo3/public/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(71): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#12 /var/www/typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#13 /var/www/typo3/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#14 /var/www/typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))\n#15 /var/www/typo3/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#16 /var/www/typo3/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#17 /var/www/typo3/public/typo3/sysext/backend/Classes/Http/Application.php(68): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#18 /var/www/typo3/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 /var/www/typo3/public/typo3/index.php(24): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#20 /var/www/typo3/public/typo3/index.php(25): {closure}()\n#21 {main}"}

```

In the meantime, I mitigated this problem by downgrading `mehrwert/phpmyadmin` back to `5.4.0` in my TYPO3 installation's `composer.json`: 

```
...
"mehrwert/phpmyadmin": "5.4.0"
...
```

**Comment by abeutel** [comment]
Hey @Abdull ,

could you please try removing your composer directory and update sources again. Maybe there is a stalled cached version in your vendor directory.

**Comment by Abdull** [comment]
I just ran into this exception on another installation again. Instead of removing some composer directory, I ran the following command:

`vendor/bin/typo3cms install:generatepackagestates`

This fixed the exception and I am able to log in the backend again.

**Comment by abeutel** [comment]
Seems to be a local composer caching issue.
